const DOT_INPUT_COLOR = 'purple'
const DOT_OUTPUT_TRUE_COLOR = 'green'
const DOT_OUTPUT_FALSE_COLOR = 'red'
const CHOOSED_DOT_COLOR = 'grey'
const IF_BLOCK_COLOR = '#6495ed'
const CHOOSED_BLOCK_COLOR = '#green'
const DOT_OUTPUT_COLOR = 'yellow'
const HTML_BLOCK_COLOR = '#36d964'